---

- hosts: all
  become: true
  tasks:

  - name: update cache
    tags: apache
    ansible.builtin.apt:
                      update_cache: yes
    when: ansible_distribution == "Ubuntu"
 
  - name: install apache2 and php support for apache packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
  
  - name: copy html file to apache
    tags: apache, apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    
  - name: install unzip
    package:
       name: unzip
  
  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
      


      
  
